feat: 32-bit support
nextcloud/user_migration pull request #408
Opened 2023-05-06 00:50 UTC by Pytal

32-bit support

`int` values overflow to `float` when greater than `PHP_INT_MAX`, see https://www.php.net/manual/en/reserved.constants.php#reserved.constants.core and https://www.php.net/manual/en/language.types.integer.php#language.types.integer.overflow

### Requires

- [ ] https://github.com/nextcloud/server/pull/38104

2023-05-09 10:13 UTC, come-nc requested changes

2023-05-09 10:13 UTC, come-nc commented on lib/Db/UserExportMapper.php
> +	public function getById(int|float $id): UserExport {
What?
No, if Id overflows there are serious problem all over Nextcloud.

2023-05-09 10:13 UTC, come-nc commented on lib/Db/UserImportMapper.php
> +	public function getById(int|float $id): UserImport {
```suggestion
	public function getById(int $id): UserImport {
```

2023-05-09 15:31 UTC, Pytal commented on lib/Db/UserExportMapper.php
> +	public function getById(int|float $id): UserExport {
🙈🆔

2023-05-11 23:50 UTC, Pytal commented
Pending automated OCP update

2023-05-15 22:59 UTC, merged