User migration foundation
nextcloud/user_migration pull request #5
Opened 2022-01-13 13:35 UTC by come-nc

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2022-01-29 00:00 UTC, Pytal commented
Rebased after https://github.com/nextcloud/user_migration/issues/24 was completed on `main` to resolve failing PHP 7.3 CI

2022-01-29 00:01 UTC, Pytal commented
Rebased after https://github.com/nextcloud/user_migration/issues/24 merged to `main` to resolve failing PHP 7.3 CI

2022-01-29 00:33 UTC, Pytal approved these changes
Solid 👌, only the occ stuff is used while the background job as well as the database related code is unused?

2022-01-31 09:40 UTC, come-nc commented
> Solid ok_hand, only the occ related stuff is used while the background job as well as the database related code is unused?

Yes maybe we can remove this for now, as the occ commands do not use the background job. We will add the background job back if it’s used is some future development. I will remove them in a commit and we can use git history later to get them back.

2022-01-31 09:42 UTC, icewind1991 requested changes

2022-01-31 09:42 UTC, icewind1991 commented on lib/ExportDestination.php
> +	public function copyFromView(View $view, string $sourcePath, string $destinationPath): bool {
This should use the newer api taking a https://github.com/nextcloud/server/blob/master/lib/public/Files/Folder.php and working from there.

2022-01-31 09:42 UTC, icewind1991 commented on lib/IImportSource.php
> +	public function copyToView(View $view, string $sourcePath, string $destinationPath): bool;
same here

2022-02-02 10:43 UTC, icewind1991 approved these changes

2022-02-03 10:32 UTC, merged